######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 30 14:19:05 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . project "Ubuntu One/programs" "Ubuntu One/programs/project"
INCLUDEPATH += .

# Input
SOURCES += 3n+1problem.c \
           a.cpp \
           a102.c \
           a103.c \
           a106.c \
           a107.c \
           a111.c \
           aa.c \
           ab.cpp \
           ac.cpp \
           againfib.c \
           alg2n.c \
           algprx.c \
           algriv.cpp \
           apoj_ae001.c \
           aran01.cpp \
           aran01a.cpp \
           arbit.cpp \
           atkins.cpp \
           atm.cpp \
           atoi.cpp \
           b.cpp \
           bestbat.cpp \
           bin_tree.cpp \
           binary.cpp \
           binary_tree.cpp \
           binary_tree_class.cpp \
           bintree_recursive.cpp \
           birthday.cpp \
           bitwiseoperators.cpp \
           bool.cpp \
           byte_bus.c \
           byte_magic.c \
           bytesa.c \
           bytesd.c \
           c3001.c \
           c3001.cpp \
           c3002.c \
           c3003.cpp \
           c3004.c \
           c3005.c \
           ca.c \
           carryovermultiplication.c \
           cc.cpp \
           cds001.c \
           cds002.c \
           cds002.cpp \
           cds003.c \
           cds005.c \
           cds007.c \
           cds007.cpp \
           choiccook.c \
           cielnum1.cpp \
           cielnum2.cpp \
           cleanup.cpp \
           clndr.cpp \
           cmb01.cpp \
           cmb02.cpp \
           cmb03.cpp \
           cmb03a.cpp \
           cme01.cpp \
           code_148a.cpp \
           codeforce160_C.cpp \
           codeforce_149a.cpp \
           codeforce_157b.cpp \
           codeforce_158a.cpp \
           codeforce_158b.cpp \
           codeforce_158c.cpp \
           codeforce_158d.c \
           codeforce_161a.cpp \
           codeforce_165a.cpp \
           codeforce_165b.cpp \
           codeforce_165c.cpp \
           codeforce_166a.cpp \
           codeforce_166c.cpp \
           codeforce_168a.cpp \
           codeforce_169a.cpp \
           codeforce_169b.cpp \
           codeforce_173a.cpp \
           codeforce_174a.cpp \
           codeforce_174b.cpp \
           codeninja_rotate.cpp \
           codesprint_game.c \
           codesprint_stock.c \
           coins.cpp \
           collide.cpp \
           cookieag.c \
           cooling.cpp \
           craft05.cpp \
           crede2.cpp \
           cs001.c \
           cs001_1.c \
           csurf_bboy.cpp \
           csurf_rmq.cpp \
           csurf_soldiers.cpp \
           d1.cpp \
           daily_train.c \
           dce05.cpp \
           dec.c \
           decstr.c \
           decstr1.c \
           depth_first_search.cpp \
           digits.cpp \
           dijkstra.cpp \
           distinctsort.cpp \
           divsum.c \
           divsum.cpp \
           dollar2.cpp \
           dollhous.c \
           double.c \
           dpc101.cpp \
           dpc204.cpp \
           dpc206.cpp \
           dumpling.cpp \
           dynamicallocation.cpp \
           election.cpp \
           euclid.cpp \
           euclid_algo.cpp \
           eulelr205.cpp \
           euler104.cpp \
           euler104a.cpp \
           euler108.cpp \
           euler11.c \
           euler11.cpp \
           euler12.cpp \
           euler13.c \
           euler14.cpp \
           euler145.cpp \
           euler15.cpp \
           euler16.cpp \
           euler164.cpp \
           euler17.cpp \
           euler179.cpp \
           euler179a.cpp \
           euler18.c \
           euler187.cpp \
           euler19.cpp \
           euler2.cpp \
           euler20.cpp \
           euler205.cpp \
           euler206.cpp \
           euler21.cpp \
           euler22.cpp \
           euler23.cpp \
           euler24.cpp \
           euler25.cpp \
           euler26.cpp \
           euler266.cpp \
           euler27.cpp \
           euler28.cpp \
           euler29.cpp \
           euler29a.cpp \
           euler29b.cpp \
           euler30.cpp \
           euler304.cpp \
           euler30a.cpp \
           euler31.cpp \
           euler31a.cpp \
           euler31b.cpp \
           euler32.cpp \
           euler33.cpp \
           euler34.cpp \
           euler35.cpp \
           euler35a.cpp \
           euler36.cpp \
           euler37.cpp \
           euler39.cpp \
           euler40.cpp \
           euler41.cpp \
           euler42.cpp \
           euler43.cpp \
           euler44.cpp \
           euler45.cpp \
           euler46.cpp \
           euler47.cpp \
           euler48.cpp \
           euler49.cpp \
           euler49a.cpp \
           euler50.cpp \
           euler51.cpp \
           euler52.cpp \
           euler52a.cpp \
           euler53.cpp \
           euler55.cpp \
           euler56.cpp \
           euler57.cpp \
           euler57a.cpp \
           euler57gmplib.cpp \
           euler58.cpp \
           euler60.cpp \
           euler63.cpp \
           euler65.cpp \
           euler67.c \
           euler69.cpp \
           euler71.cpp \
           euler75.cpp \
           euler76.cpp \
           euler80.cpp \
           euler81.c \
           euler85.cpp \
           euler87.cpp \
           euler92.cpp \
           euler95.cpp \
           euler97.cpp \
           euler99.cpp \
           exact_money_problem.cpp \
           exp_by_squaring.c \
           fact.c \
           factorialcodechef.cpp \
           fast_input_output.cpp \
           fast_read_intest.cpp \
           fb.cpp \
           fctrl2cc.cpp \
           file_handle_c.cpp \
           gmp.cpp \
           gmpclass.cpp \
           gmpstring.cpp \
           hdeliver.c \
           hdeliver.cpp \
           hdeliver1.c \
           helpdigo.cpp \
           helpdigo1.cpp \
           holes.cpp \
           iiti00.cpp \
           iiti03.c \
           iitvsiit.cpp \
           insoma3.c \
           insoma3_merge_sort.c \
           interview_1.c \
           intestcc.cpp \
           knapsack.c \
           knapsack.cpp \
           kur1.cpp \
           l5.cpp \
           large_multiplication.c \
           largefact.c \
           largeno_prime.cpp \
           layout_cpp.cpp \
           life.cpp \
           link_list.cpp \
           link_list_tail.cpp \
           linked_list.cpp \
           lm.c \
           luck_conv.cpp \
           lucky5.cpp \
           lucky5a.cpp \
           magiduel.c \
           manip2.cpp \
           max_sum_figure_triangle.cpp \
           maxcount.cpp \
           misint2.cpp \
           misint22.cpp \
           mixtures.cpp \
           mod_1000000007.c \
           mod_10^9+7.c \
           newton_raphson_method.c \
           nopc.c \
           nopc10.cpp \
           nopc3.cpp \
           nopc4.cpp \
           nopc6.c \
           nopc7.cpp \
           nopc8.cpp \
           nopc9.cpp \
           nsit13.cpp \
           nsit15.cpp \
           nukes.c \
           nukes.cpp \
           numgame.cpp \
           numgamea.cpp \
           palin.cpp \
           palina.cpp \
           palindrome.cpp \
           panstack.c \
           panstack.cpp \
           part3way.c \
           pasin.c \
           pasin.cpp \
           paying_up.c \
           paying_up.cpp \
           pcount.cpp \
           pcycle.c \
           pcycle1.c \
           pd11.c \
           pd12.c \
           permut.cpp \
           permute.c \
           pi-gmp.cpp \
           playfit.cpp \
           points.cpp \
           points1.cpp \
           poker.cpp \
           prayas01.cpp \
           prayas04.cpp \
           prime-eratosthenes.cpp \
           prime-sieve.cpp \
           prime.cpp \
           primea.cpp \
           primesieve.cpp \
           properdivisor.cpp \
           prpalin.cpp \
           qt.cpp \
           rbx12r04.c \
           readint.cpp \
           readstring.cpp \
           recipe.cpp \
           recur.c \
           recursion.cpp \
           resist.c \
           resn04.cpp \
           reverse.cpp \
           rgpvr103.c \
           rhouse.cpp \
           rohan.cpp \
           samedigits.cpp \
           samplecodechef.cpp \
           shorten.c \
           shuttle.c \
           shuttle.cpp \
           simgraph.c \
           simplesum.c \
           simplfib.c \
           sort2-darray.cpp \
           sorting.cpp \
           sortingfast.cpp \
           sortstring.cpp \
           spj_fence1.c \
           spoj_aba12a.c \
           spoj_absys.cpp \
           spoj_acpc10a.c \
           spoj_acpc11a.cpp \
           spoj_acpc11b.cpp \
           spoj_addrev.cpp \
           spoj_adun.c \
           spoj_adv04j.c \
           spoj_ae00.c \
           spoj_ae1b.c \
           spoj_ae1b.cpp \
           spoj_aggrcow.cpp \
           spoj_aibohp.cpp \
           spoj_alche.c \
           spoj_alicesie.c \
           spoj_amr10f.c \
           spoj_amr10g.cpp \
           spoj_amr11e.cpp \
           spoj_amr11g.c \
           spoj_anarc05b.cpp \
           spoj_anarc08e.c \
           spoj_anarc09a.cpp \
           spoj_and.cpp \
           spoj_ap2.cpp \
           spoj_ap3.cpp \
           spoj_arith2.c \
           spoj_arith2_1.c \
           spoj_army.c \
           spoj_assist.c \
           spoj_avion1.c \
           spoj_bankrobb.cpp \
           spoj_beads.cpp \
           spoj_beenums.c \
           spoj_bishops.c \
           spoj_bitcntr.c \
           spoj_bitmap.cpp \
           spoj_byecakes.c \
           spoj_bytesm2.c \
           spoj_candy.c \
           spoj_candy3.c \
           spoj_canton.c \
           spoj_clone.cpp \
           spoj_coins.c \
           spoj_cprmt.cpp \
           spoj_crds.c \
           spoj_danger.cpp \
           spoj_dcepc206.c \
           spoj_divsum.c \
           spoj_drink.c \
           spoj_eboxes.c \
           spoj_edist.c \
           spoj_edit.c \
           spoj_egypizza.c \
           spoj_eights.c \
           spoj_etf.c \
           spoj_etf.cpp \
           spoj_etfa.c \
           spoj_exfor.cpp \
           spoj_familyp.c \
           spoj_fashion.c \
           spoj_fctrl.cpp \
           spoj_feeluck.cpp \
           spoj_fibosum.cpp \
           spoj_girlsnbs.c \
           spoj_gljive.cpp \
           spoj_gny07a.cpp \
           spoj_gny07b.c \
           spoj_gp1.cpp \
           spoj_gss1.cpp \
           spoj_guessthe.c \
           spoj_hangover.c \
           spoj_hellokit.c \
           spoj_hpynos.c \
           spoj_hpynos.cpp \
           spoj_hubullu.cpp \
           spoj_intest.c \
           spoj_invcnt.c \
           spoj_iwgbs.c \
           spoj_javac.c \
           spoj_lastdig.c \
           spoj_lastdiga.c \
           spoj_looksay.cpp \
           spoj_main12d.cpp \
           spoj_main72.cpp \
           spoj_major.c \
           spoj_marbles.c \
           spoj_maxinarr.c \
           spoj_maxln.cpp \
           spoj_maya.c \
           spoj_mflar10.cpp \
           spoj_mincount.c \
           spoj_miserman.c \
           spoj_mrecaman.cpp \
           spoj_multq3.c \
           spoj_myq1.c \
           spoj_ngm.cpp \
           spoj_nsteps.cpp \
           spoj_numofpal.c \
           spoj_ny10a.c \
           spoj_offside.cpp \
           spoj_ololo.cpp \
           spoj_palin.cpp \
           spoj_pdecode.cpp \
           spoj_permut2.c \
           spoj_pigbank.cpp \
           spoj_pigbank1.cpp \
           spoj_pir.cpp \
           spoj_plusevi.cpp \
           spoj_poleval.c \
           spoj_pt07y.c \
           spoj_quadarea.c \
           spoj_quality.c \
           spoj_resn04.c \
           spoj_rootciph.c \
           spoj_samer08f.cpp \
           spoj_scpc11d.c \
           spoj_shell.cpp \
           spoj_silver.c \
           spoj_sprlnms.c \
           spoj_stamps.c \
           spoj_stpar.c \
           spoj_sub_prob.c \
           spoj_sumfour.cpp \
           spoj_sumitr.c \
           spoj_tetra.cpp \
           spoj_tmul.c \
           spoj_toandfro.cpp \
           spoj_tricount.c \
           spoj_trigalge.c \
           spoj_triz.c \
           spoj_trt.cpp \
           spoj_twosqrs.c \
           spoj_verodoom.c \
           spoj_vudaab.c \
           spoj_willitst.cpp \
           spoj_words1.cpp \
           spoj_wpc4f.c \
           spoon.c \
           spoon_1.c \
           stl_vector.cpp \
           string.cpp \
           sumtrian.c \
           sumtrian.cpp \
           switch.cpp \
           tech04.cpp \
           tlg.cpp \
           tsort.cpp \
           twosqrs.c \
           twosqrs.cpp \
           viru.cpp \
           voters.cpp \
           warzone2.c \
           wcount.cpp \
           wcount1.c \
           wcount2.c \
           wcount3.c \
           wcounta.cpp \
           wintakal.cpp \
           project/encrpyt_full.c \
           project/encrypt.c \
           project/encrypt_alphanumeric.c \
           project/encrypt_check.c \
           project/encrypt_file.c \
           project/encrypt_general.c \
           project/test.c \
           project/test1.c \
           project/test2.c \
           project/test3.c \
           "Ubuntu One/programs/3n+1problem.c" \
           "Ubuntu One/programs/a.cpp" \
           "Ubuntu One/programs/a102.c" \
           "Ubuntu One/programs/a103.c" \
           "Ubuntu One/programs/a106.c" \
           "Ubuntu One/programs/a107.c" \
           "Ubuntu One/programs/a111.c" \
           "Ubuntu One/programs/aa.c" \
           "Ubuntu One/programs/ab.cpp" \
           "Ubuntu One/programs/ac.cpp" \
           "Ubuntu One/programs/againfib.c" \
           "Ubuntu One/programs/alg2n.c" \
           "Ubuntu One/programs/algprx.c" \
           "Ubuntu One/programs/algriv.cpp" \
           "Ubuntu One/programs/apoj_ae001.c" \
           "Ubuntu One/programs/aran01.cpp" \
           "Ubuntu One/programs/aran01a.cpp" \
           "Ubuntu One/programs/arbit.cpp" \
           "Ubuntu One/programs/atkins.cpp" \
           "Ubuntu One/programs/atm.cpp" \
           "Ubuntu One/programs/atoi.cpp" \
           "Ubuntu One/programs/b.cpp" \
           "Ubuntu One/programs/bestbat.cpp" \
           "Ubuntu One/programs/bin_tree.cpp" \
           "Ubuntu One/programs/binary.cpp" \
           "Ubuntu One/programs/binary_tree.cpp" \
           "Ubuntu One/programs/binary_tree_class.cpp" \
           "Ubuntu One/programs/bintree_recursive.cpp" \
           "Ubuntu One/programs/birthday.cpp" \
           "Ubuntu One/programs/bitwiseoperators.cpp" \
           "Ubuntu One/programs/bool.cpp" \
           "Ubuntu One/programs/byte_bus.c" \
           "Ubuntu One/programs/byte_magic.c" \
           "Ubuntu One/programs/bytesa.c" \
           "Ubuntu One/programs/bytesd.c" \
           "Ubuntu One/programs/c3001.c" \
           "Ubuntu One/programs/c3001.cpp" \
           "Ubuntu One/programs/c3002.c" \
           "Ubuntu One/programs/c3003.cpp" \
           "Ubuntu One/programs/c3004.c" \
           "Ubuntu One/programs/c3005.c" \
           "Ubuntu One/programs/ca.c" \
           "Ubuntu One/programs/carryovermultiplication.c" \
           "Ubuntu One/programs/cc.cpp" \
           "Ubuntu One/programs/cds001.c" \
           "Ubuntu One/programs/cds002.c" \
           "Ubuntu One/programs/cds002.cpp" \
           "Ubuntu One/programs/cds003.c" \
           "Ubuntu One/programs/cds005.c" \
           "Ubuntu One/programs/cds007.c" \
           "Ubuntu One/programs/cds007.cpp" \
           "Ubuntu One/programs/choiccook.c" \
           "Ubuntu One/programs/cielnum1.cpp" \
           "Ubuntu One/programs/cielnum2.cpp" \
           "Ubuntu One/programs/cleanup.cpp" \
           "Ubuntu One/programs/clndr.cpp" \
           "Ubuntu One/programs/cmb01.cpp" \
           "Ubuntu One/programs/cmb02.cpp" \
           "Ubuntu One/programs/cmb03.cpp" \
           "Ubuntu One/programs/cmb03a.cpp" \
           "Ubuntu One/programs/cme01.cpp" \
           "Ubuntu One/programs/code_148a.cpp" \
           "Ubuntu One/programs/codeforce160_C.cpp" \
           "Ubuntu One/programs/codeforce_149a.cpp" \
           "Ubuntu One/programs/codeforce_157b.cpp" \
           "Ubuntu One/programs/codeforce_158a.cpp" \
           "Ubuntu One/programs/codeforce_158b.cpp" \
           "Ubuntu One/programs/codeforce_158c.cpp" \
           "Ubuntu One/programs/codeforce_158d.c" \
           "Ubuntu One/programs/codeforce_161a.cpp" \
           "Ubuntu One/programs/codeforce_165a.cpp" \
           "Ubuntu One/programs/codeforce_165b.cpp" \
           "Ubuntu One/programs/codeforce_165c.cpp" \
           "Ubuntu One/programs/codeforce_166a.cpp" \
           "Ubuntu One/programs/codeforce_166c.cpp" \
           "Ubuntu One/programs/codeforce_168a.cpp" \
           "Ubuntu One/programs/codeforce_169a.cpp" \
           "Ubuntu One/programs/codeforce_169b.cpp" \
           "Ubuntu One/programs/codeforce_173a.cpp" \
           "Ubuntu One/programs/codeforce_174a.cpp" \
           "Ubuntu One/programs/codeforce_174b.cpp" \
           "Ubuntu One/programs/codeninja_rotate.cpp" \
           "Ubuntu One/programs/codesprint_game.c" \
           "Ubuntu One/programs/codesprint_stock.c" \
           "Ubuntu One/programs/coins.cpp" \
           "Ubuntu One/programs/collide.cpp" \
           "Ubuntu One/programs/cookieag.c" \
           "Ubuntu One/programs/cooling.cpp" \
           "Ubuntu One/programs/craft05.cpp" \
           "Ubuntu One/programs/crede2.cpp" \
           "Ubuntu One/programs/cs001.c" \
           "Ubuntu One/programs/cs001_1.c" \
           "Ubuntu One/programs/csurf_bboy.cpp" \
           "Ubuntu One/programs/csurf_rmq.cpp" \
           "Ubuntu One/programs/csurf_soldiers.cpp" \
           "Ubuntu One/programs/d1.cpp" \
           "Ubuntu One/programs/daily_train.c" \
           "Ubuntu One/programs/dce05.cpp" \
           "Ubuntu One/programs/dec.c" \
           "Ubuntu One/programs/decstr.c" \
           "Ubuntu One/programs/decstr1.c" \
           "Ubuntu One/programs/depth_first_search.cpp" \
           "Ubuntu One/programs/digits.cpp" \
           "Ubuntu One/programs/dijkstra.cpp" \
           "Ubuntu One/programs/distinctsort.cpp" \
           "Ubuntu One/programs/divsum.c" \
           "Ubuntu One/programs/divsum.cpp" \
           "Ubuntu One/programs/dollar2.cpp" \
           "Ubuntu One/programs/dollhous.c" \
           "Ubuntu One/programs/double.c" \
           "Ubuntu One/programs/dpc101.cpp" \
           "Ubuntu One/programs/dpc204.cpp" \
           "Ubuntu One/programs/dpc206.cpp" \
           "Ubuntu One/programs/dumpling.cpp" \
           "Ubuntu One/programs/dynamicallocation.cpp" \
           "Ubuntu One/programs/election.cpp" \
           "Ubuntu One/programs/euclid.cpp" \
           "Ubuntu One/programs/euclid_algo.cpp" \
           "Ubuntu One/programs/eulelr205.cpp" \
           "Ubuntu One/programs/euler104.cpp" \
           "Ubuntu One/programs/euler104a.cpp" \
           "Ubuntu One/programs/euler108.cpp" \
           "Ubuntu One/programs/euler11.c" \
           "Ubuntu One/programs/euler11.cpp" \
           "Ubuntu One/programs/euler12.cpp" \
           "Ubuntu One/programs/euler13.c" \
           "Ubuntu One/programs/euler14.cpp" \
           "Ubuntu One/programs/euler145.cpp" \
           "Ubuntu One/programs/euler15.cpp" \
           "Ubuntu One/programs/euler16.cpp" \
           "Ubuntu One/programs/euler164.cpp" \
           "Ubuntu One/programs/euler17.cpp" \
           "Ubuntu One/programs/euler179.cpp" \
           "Ubuntu One/programs/euler179a.cpp" \
           "Ubuntu One/programs/euler18.c" \
           "Ubuntu One/programs/euler187.cpp" \
           "Ubuntu One/programs/euler19.cpp" \
           "Ubuntu One/programs/euler2.cpp" \
           "Ubuntu One/programs/euler20.cpp" \
           "Ubuntu One/programs/euler205.cpp" \
           "Ubuntu One/programs/euler206.cpp" \
           "Ubuntu One/programs/euler21.cpp" \
           "Ubuntu One/programs/euler22.cpp" \
           "Ubuntu One/programs/euler23.cpp" \
           "Ubuntu One/programs/euler24.cpp" \
           "Ubuntu One/programs/euler25.cpp" \
           "Ubuntu One/programs/euler26.cpp" \
           "Ubuntu One/programs/euler266.cpp" \
           "Ubuntu One/programs/euler27.cpp" \
           "Ubuntu One/programs/euler28.cpp" \
           "Ubuntu One/programs/euler29.cpp" \
           "Ubuntu One/programs/euler29a.cpp" \
           "Ubuntu One/programs/euler29b.cpp" \
           "Ubuntu One/programs/euler30.cpp" \
           "Ubuntu One/programs/euler304.cpp" \
           "Ubuntu One/programs/euler30a.cpp" \
           "Ubuntu One/programs/euler31.cpp" \
           "Ubuntu One/programs/euler31a.cpp" \
           "Ubuntu One/programs/euler31b.cpp" \
           "Ubuntu One/programs/euler32.cpp" \
           "Ubuntu One/programs/euler33.cpp" \
           "Ubuntu One/programs/euler34.cpp" \
           "Ubuntu One/programs/euler35.cpp" \
           "Ubuntu One/programs/euler35a.cpp" \
           "Ubuntu One/programs/euler36.cpp" \
           "Ubuntu One/programs/euler37.cpp" \
           "Ubuntu One/programs/euler39.cpp" \
           "Ubuntu One/programs/euler40.cpp" \
           "Ubuntu One/programs/euler41.cpp" \
           "Ubuntu One/programs/euler42.cpp" \
           "Ubuntu One/programs/euler43.cpp" \
           "Ubuntu One/programs/euler44.cpp" \
           "Ubuntu One/programs/euler45.cpp" \
           "Ubuntu One/programs/euler46.cpp" \
           "Ubuntu One/programs/euler47.cpp" \
           "Ubuntu One/programs/euler48.cpp" \
           "Ubuntu One/programs/euler49.cpp" \
           "Ubuntu One/programs/euler49a.cpp" \
           "Ubuntu One/programs/euler50.cpp" \
           "Ubuntu One/programs/euler51.cpp" \
           "Ubuntu One/programs/euler52.cpp" \
           "Ubuntu One/programs/euler52a.cpp" \
           "Ubuntu One/programs/euler53.cpp" \
           "Ubuntu One/programs/euler55.cpp" \
           "Ubuntu One/programs/euler56.cpp" \
           "Ubuntu One/programs/euler57.cpp" \
           "Ubuntu One/programs/euler57a.cpp" \
           "Ubuntu One/programs/euler57gmplib.cpp" \
           "Ubuntu One/programs/euler58.cpp" \
           "Ubuntu One/programs/euler60.cpp" \
           "Ubuntu One/programs/euler63.cpp" \
           "Ubuntu One/programs/euler65.cpp" \
           "Ubuntu One/programs/euler67.c" \
           "Ubuntu One/programs/euler69.cpp" \
           "Ubuntu One/programs/euler71.cpp" \
           "Ubuntu One/programs/euler75.cpp" \
           "Ubuntu One/programs/euler76.cpp" \
           "Ubuntu One/programs/euler80.cpp" \
           "Ubuntu One/programs/euler81.c" \
           "Ubuntu One/programs/euler85.cpp" \
           "Ubuntu One/programs/euler87.cpp" \
           "Ubuntu One/programs/euler92.cpp" \
           "Ubuntu One/programs/euler95.cpp" \
           "Ubuntu One/programs/euler97.cpp" \
           "Ubuntu One/programs/euler99.cpp" \
           "Ubuntu One/programs/exact_money_problem.cpp" \
           "Ubuntu One/programs/exp_by_squaring.c" \
           "Ubuntu One/programs/fact.c" \
           "Ubuntu One/programs/factorialcodechef.cpp" \
           "Ubuntu One/programs/fast_input_output.cpp" \
           "Ubuntu One/programs/fast_read_intest.cpp" \
           "Ubuntu One/programs/fb.cpp" \
           "Ubuntu One/programs/fctrl2cc.cpp" \
           "Ubuntu One/programs/file_handle_c.cpp" \
           "Ubuntu One/programs/gmp.cpp" \
           "Ubuntu One/programs/gmpclass.cpp" \
           "Ubuntu One/programs/gmpstring.cpp" \
           "Ubuntu One/programs/hdeliver.c" \
           "Ubuntu One/programs/hdeliver.cpp" \
           "Ubuntu One/programs/hdeliver1.c" \
           "Ubuntu One/programs/helpdigo.cpp" \
           "Ubuntu One/programs/helpdigo1.cpp" \
           "Ubuntu One/programs/holes.cpp" \
           "Ubuntu One/programs/iiti00.cpp" \
           "Ubuntu One/programs/iiti03.c" \
           "Ubuntu One/programs/iitvsiit.cpp" \
           "Ubuntu One/programs/insoma3.c" \
           "Ubuntu One/programs/insoma3_merge_sort.c" \
           "Ubuntu One/programs/interview_1.c" \
           "Ubuntu One/programs/intestcc.cpp" \
           "Ubuntu One/programs/knapsack.c" \
           "Ubuntu One/programs/knapsack.cpp" \
           "Ubuntu One/programs/kur1.cpp" \
           "Ubuntu One/programs/l5.cpp" \
           "Ubuntu One/programs/large_multiplication.c" \
           "Ubuntu One/programs/largefact.c" \
           "Ubuntu One/programs/largeno_prime.cpp" \
           "Ubuntu One/programs/layout_cpp.cpp" \
           "Ubuntu One/programs/life.cpp" \
           "Ubuntu One/programs/link_list.cpp" \
           "Ubuntu One/programs/link_list_tail.cpp" \
           "Ubuntu One/programs/linked_list.cpp" \
           "Ubuntu One/programs/lm.c" \
           "Ubuntu One/programs/luck_conv.cpp" \
           "Ubuntu One/programs/lucky5.cpp" \
           "Ubuntu One/programs/lucky5a.cpp" \
           "Ubuntu One/programs/magiduel.c" \
           "Ubuntu One/programs/manip2.cpp" \
           "Ubuntu One/programs/max_sum_figure_triangle.cpp" \
           "Ubuntu One/programs/maxcount.cpp" \
           "Ubuntu One/programs/misint2.cpp" \
           "Ubuntu One/programs/misint22.cpp" \
           "Ubuntu One/programs/mixtures.cpp" \
           "Ubuntu One/programs/mod_1000000007.c" \
           "Ubuntu One/programs/mod_10^9+7.c" \
           "Ubuntu One/programs/newton_raphson_method.c" \
           "Ubuntu One/programs/nopc.c" \
           "Ubuntu One/programs/nopc10.cpp" \
           "Ubuntu One/programs/nopc3.cpp" \
           "Ubuntu One/programs/nopc4.cpp" \
           "Ubuntu One/programs/nopc6.c" \
           "Ubuntu One/programs/nopc7.cpp" \
           "Ubuntu One/programs/nopc8.cpp" \
           "Ubuntu One/programs/nopc9.cpp" \
           "Ubuntu One/programs/nsit13.cpp" \
           "Ubuntu One/programs/nsit15.cpp" \
           "Ubuntu One/programs/nukes.c" \
           "Ubuntu One/programs/nukes.cpp" \
           "Ubuntu One/programs/numgame.cpp" \
           "Ubuntu One/programs/numgamea.cpp" \
           "Ubuntu One/programs/palin.cpp" \
           "Ubuntu One/programs/palina.cpp" \
           "Ubuntu One/programs/palindrome.cpp" \
           "Ubuntu One/programs/panstack.c" \
           "Ubuntu One/programs/panstack.cpp" \
           "Ubuntu One/programs/part3way.c" \
           "Ubuntu One/programs/pasin.c" \
           "Ubuntu One/programs/pasin.cpp" \
           "Ubuntu One/programs/paying_up.c" \
           "Ubuntu One/programs/paying_up.cpp" \
           "Ubuntu One/programs/pcount.cpp" \
           "Ubuntu One/programs/pcycle.c" \
           "Ubuntu One/programs/pcycle1.c" \
           "Ubuntu One/programs/pd11.c" \
           "Ubuntu One/programs/pd12.c" \
           "Ubuntu One/programs/permut.cpp" \
           "Ubuntu One/programs/permute.c" \
           "Ubuntu One/programs/pi-gmp.cpp" \
           "Ubuntu One/programs/playfit.cpp" \
           "Ubuntu One/programs/points.cpp" \
           "Ubuntu One/programs/points1.cpp" \
           "Ubuntu One/programs/poker.cpp" \
           "Ubuntu One/programs/prayas01.cpp" \
           "Ubuntu One/programs/prayas04.cpp" \
           "Ubuntu One/programs/prime-eratosthenes.cpp" \
           "Ubuntu One/programs/prime-sieve.cpp" \
           "Ubuntu One/programs/prime.cpp" \
           "Ubuntu One/programs/primea.cpp" \
           "Ubuntu One/programs/primesieve.cpp" \
           "Ubuntu One/programs/properdivisor.cpp" \
           "Ubuntu One/programs/prpalin.cpp" \
           "Ubuntu One/programs/rbx12r04.c" \
           "Ubuntu One/programs/readint.cpp" \
           "Ubuntu One/programs/readstring.cpp" \
           "Ubuntu One/programs/recipe.cpp" \
           "Ubuntu One/programs/recur.c" \
           "Ubuntu One/programs/recursion.cpp" \
           "Ubuntu One/programs/resist.c" \
           "Ubuntu One/programs/resn04.cpp" \
           "Ubuntu One/programs/reverse.cpp" \
           "Ubuntu One/programs/rgpvr103.c" \
           "Ubuntu One/programs/rhouse.cpp" \
           "Ubuntu One/programs/rohan.cpp" \
           "Ubuntu One/programs/samedigits.cpp" \
           "Ubuntu One/programs/samplecodechef.cpp" \
           "Ubuntu One/programs/shorten.c" \
           "Ubuntu One/programs/shuttle.c" \
           "Ubuntu One/programs/shuttle.cpp" \
           "Ubuntu One/programs/simgraph.c" \
           "Ubuntu One/programs/simplesum.c" \
           "Ubuntu One/programs/simplfib.c" \
           "Ubuntu One/programs/sort2-darray.cpp" \
           "Ubuntu One/programs/sorting.cpp" \
           "Ubuntu One/programs/sortingfast.cpp" \
           "Ubuntu One/programs/sortstring.cpp" \
           "Ubuntu One/programs/spj_fence1.c" \
           "Ubuntu One/programs/spoj_aba12a.c" \
           "Ubuntu One/programs/spoj_absys.cpp" \
           "Ubuntu One/programs/spoj_acpc10a.c" \
           "Ubuntu One/programs/spoj_acpc11a.cpp" \
           "Ubuntu One/programs/spoj_acpc11b.cpp" \
           "Ubuntu One/programs/spoj_addrev.cpp" \
           "Ubuntu One/programs/spoj_adun.c" \
           "Ubuntu One/programs/spoj_adv04j.c" \
           "Ubuntu One/programs/spoj_ae00.c" \
           "Ubuntu One/programs/spoj_ae1b.c" \
           "Ubuntu One/programs/spoj_ae1b.cpp" \
           "Ubuntu One/programs/spoj_aggrcow.cpp" \
           "Ubuntu One/programs/spoj_aibohp.cpp" \
           "Ubuntu One/programs/spoj_alche.c" \
           "Ubuntu One/programs/spoj_alicesie.c" \
           "Ubuntu One/programs/spoj_amr10f.c" \
           "Ubuntu One/programs/spoj_amr10g.cpp" \
           "Ubuntu One/programs/spoj_amr11e.cpp" \
           "Ubuntu One/programs/spoj_amr11g.c" \
           "Ubuntu One/programs/spoj_anarc05b.cpp" \
           "Ubuntu One/programs/spoj_anarc08e.c" \
           "Ubuntu One/programs/spoj_anarc09a.cpp" \
           "Ubuntu One/programs/spoj_and.cpp" \
           "Ubuntu One/programs/spoj_ap2.cpp" \
           "Ubuntu One/programs/spoj_ap3.cpp" \
           "Ubuntu One/programs/spoj_arith2.c" \
           "Ubuntu One/programs/spoj_arith2_1.c" \
           "Ubuntu One/programs/spoj_army.c" \
           "Ubuntu One/programs/spoj_assist.c" \
           "Ubuntu One/programs/spoj_avion1.c" \
           "Ubuntu One/programs/spoj_bankrobb.cpp" \
           "Ubuntu One/programs/spoj_beads.cpp" \
           "Ubuntu One/programs/spoj_beenums.c" \
           "Ubuntu One/programs/spoj_bishops.c" \
           "Ubuntu One/programs/spoj_bitcntr.c" \
           "Ubuntu One/programs/spoj_bitmap.cpp" \
           "Ubuntu One/programs/spoj_byecakes.c" \
           "Ubuntu One/programs/spoj_bytesm2.c" \
           "Ubuntu One/programs/spoj_candy.c" \
           "Ubuntu One/programs/spoj_candy3.c" \
           "Ubuntu One/programs/spoj_canton.c" \
           "Ubuntu One/programs/spoj_clone.cpp" \
           "Ubuntu One/programs/spoj_coins.c" \
           "Ubuntu One/programs/spoj_cprmt.cpp" \
           "Ubuntu One/programs/spoj_crds.c" \
           "Ubuntu One/programs/spoj_danger.cpp" \
           "Ubuntu One/programs/spoj_dcepc206.c" \
           "Ubuntu One/programs/spoj_divsum.c" \
           "Ubuntu One/programs/spoj_drink.c" \
           "Ubuntu One/programs/spoj_eboxes.c" \
           "Ubuntu One/programs/spoj_edist.c" \
           "Ubuntu One/programs/spoj_edit.c" \
           "Ubuntu One/programs/spoj_egypizza.c" \
           "Ubuntu One/programs/spoj_eights.c" \
           "Ubuntu One/programs/spoj_etf.c" \
           "Ubuntu One/programs/spoj_etf.cpp" \
           "Ubuntu One/programs/spoj_etfa.c" \
           "Ubuntu One/programs/spoj_exfor.cpp" \
           "Ubuntu One/programs/spoj_familyp.c" \
           "Ubuntu One/programs/spoj_fashion.c" \
           "Ubuntu One/programs/spoj_fctrl.cpp" \
           "Ubuntu One/programs/spoj_feeluck.cpp" \
           "Ubuntu One/programs/spoj_fibosum.cpp" \
           "Ubuntu One/programs/spoj_girlsnbs.c" \
           "Ubuntu One/programs/spoj_gljive.cpp" \
           "Ubuntu One/programs/spoj_gny07a.cpp" \
           "Ubuntu One/programs/spoj_gny07b.c" \
           "Ubuntu One/programs/spoj_gp1.cpp" \
           "Ubuntu One/programs/spoj_gss1.cpp" \
           "Ubuntu One/programs/spoj_guessthe.c" \
           "Ubuntu One/programs/spoj_hangover.c" \
           "Ubuntu One/programs/spoj_hellokit.c" \
           "Ubuntu One/programs/spoj_hpynos.c" \
           "Ubuntu One/programs/spoj_hpynos.cpp" \
           "Ubuntu One/programs/spoj_hubullu.cpp" \
           "Ubuntu One/programs/spoj_intest.c" \
           "Ubuntu One/programs/spoj_invcnt.c" \
           "Ubuntu One/programs/spoj_iwgbs.c" \
           "Ubuntu One/programs/spoj_javac.c" \
           "Ubuntu One/programs/spoj_lastdig.c" \
           "Ubuntu One/programs/spoj_lastdiga.c" \
           "Ubuntu One/programs/spoj_looksay.cpp" \
           "Ubuntu One/programs/spoj_main12d.cpp" \
           "Ubuntu One/programs/spoj_main72.cpp" \
           "Ubuntu One/programs/spoj_major.c" \
           "Ubuntu One/programs/spoj_marbles.c" \
           "Ubuntu One/programs/spoj_maxinarr.c" \
           "Ubuntu One/programs/spoj_maxln.cpp" \
           "Ubuntu One/programs/spoj_maya.c" \
           "Ubuntu One/programs/spoj_mflar10.cpp" \
           "Ubuntu One/programs/spoj_mincount.c" \
           "Ubuntu One/programs/spoj_miserman.c" \
           "Ubuntu One/programs/spoj_mrecaman.cpp" \
           "Ubuntu One/programs/spoj_multq3.c" \
           "Ubuntu One/programs/spoj_myq1.c" \
           "Ubuntu One/programs/spoj_ngm.cpp" \
           "Ubuntu One/programs/spoj_nsteps.cpp" \
           "Ubuntu One/programs/spoj_numofpal.c" \
           "Ubuntu One/programs/spoj_ny10a.c" \
           "Ubuntu One/programs/spoj_offside.cpp" \
           "Ubuntu One/programs/spoj_ololo.cpp" \
           "Ubuntu One/programs/spoj_palin.cpp" \
           "Ubuntu One/programs/spoj_pdecode.cpp" \
           "Ubuntu One/programs/spoj_permut2.c" \
           "Ubuntu One/programs/spoj_pigbank.cpp" \
           "Ubuntu One/programs/spoj_pigbank1.cpp" \
           "Ubuntu One/programs/spoj_pir.cpp" \
           "Ubuntu One/programs/spoj_plusevi.cpp" \
           "Ubuntu One/programs/spoj_poleval.c" \
           "Ubuntu One/programs/spoj_pt07y.c" \
           "Ubuntu One/programs/spoj_quadarea.c" \
           "Ubuntu One/programs/spoj_quality.c" \
           "Ubuntu One/programs/spoj_resn04.c" \
           "Ubuntu One/programs/spoj_rootciph.c" \
           "Ubuntu One/programs/spoj_samer08f.cpp" \
           "Ubuntu One/programs/spoj_scpc11d.c" \
           "Ubuntu One/programs/spoj_shell.cpp" \
           "Ubuntu One/programs/spoj_silver.c" \
           "Ubuntu One/programs/spoj_sprlnms.c" \
           "Ubuntu One/programs/spoj_stamps.c" \
           "Ubuntu One/programs/spoj_stpar.c" \
           "Ubuntu One/programs/spoj_sub_prob.c" \
           "Ubuntu One/programs/spoj_sumfour.cpp" \
           "Ubuntu One/programs/spoj_sumitr.c" \
           "Ubuntu One/programs/spoj_tetra.cpp" \
           "Ubuntu One/programs/spoj_tmul.c" \
           "Ubuntu One/programs/spoj_toandfro.cpp" \
           "Ubuntu One/programs/spoj_tricount.c" \
           "Ubuntu One/programs/spoj_trigalge.c" \
           "Ubuntu One/programs/spoj_triz.c" \
           "Ubuntu One/programs/spoj_trt.cpp" \
           "Ubuntu One/programs/spoj_twosqrs.c" \
           "Ubuntu One/programs/spoj_verodoom.c" \
           "Ubuntu One/programs/spoj_vudaab.c" \
           "Ubuntu One/programs/spoj_willitst.cpp" \
           "Ubuntu One/programs/spoj_words1.cpp" \
           "Ubuntu One/programs/spoj_wpc4f.c" \
           "Ubuntu One/programs/spoon.c" \
           "Ubuntu One/programs/spoon_1.c" \
           "Ubuntu One/programs/stl_vector.cpp" \
           "Ubuntu One/programs/string.cpp" \
           "Ubuntu One/programs/sumtrian.c" \
           "Ubuntu One/programs/sumtrian.cpp" \
           "Ubuntu One/programs/switch.cpp" \
           "Ubuntu One/programs/tech04.cpp" \
           "Ubuntu One/programs/tlg.cpp" \
           "Ubuntu One/programs/tsort.cpp" \
           "Ubuntu One/programs/twosqrs.c" \
           "Ubuntu One/programs/twosqrs.cpp" \
           "Ubuntu One/programs/viru.cpp" \
           "Ubuntu One/programs/voters.cpp" \
           "Ubuntu One/programs/warzone2.c" \
           "Ubuntu One/programs/wcount.cpp" \
           "Ubuntu One/programs/wcount1.c" \
           "Ubuntu One/programs/wcount2.c" \
           "Ubuntu One/programs/wcount3.c" \
           "Ubuntu One/programs/wcounta.cpp" \
           "Ubuntu One/programs/wintakal.cpp" \
           "Ubuntu One/programs/project/encrpyt_full.c" \
           "Ubuntu One/programs/project/encrypt.c" \
           "Ubuntu One/programs/project/encrypt_alphanumeric.c" \
           "Ubuntu One/programs/project/encrypt_check.c" \
           "Ubuntu One/programs/project/encrypt_file.c" \
           "Ubuntu One/programs/project/encrypt_general.c" \
           "Ubuntu One/programs/project/test.c" \
           "Ubuntu One/programs/project/test1.c" \
           "Ubuntu One/programs/project/test2.c" \
           "Ubuntu One/programs/project/test3.c"
