######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 30 14:32:04 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qt.cpp
